openapi: 3.0.0
info:
  title: Drivers list
  version: 0.0.1
servers:
  - url: http://localhost:5000/api/v1/report/
    description: Dev server
paths:
  /drivers:
    get:
      summary: Get Divers list
      tags:
        - Drivers
      operationId: getAllDrivers
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drivers'
        'default':
          description: All Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
#  /drivers/{driver_code}:
#    get:
#      summary: Get Diver by code
#      tags:
#        - Drivers
#      operationId: getDriverById
#      parameters:
#        - name: driver_code
#          in: path
#          required: true
#          description: driver_code
#          schema:
#            type: string
#          example: SVF
#      responses:
#        "200":
#          description: Successful response
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Drivers'
#        'default':
#          description: All Errors
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Error'
              
              
components:
  schemas:
    Driver:
      type: object
      required:
        - number
        - name
        - company
        - result
      properties:
        driver_code:
          type: string
          example: SVF
        number:
          type: string
          example: 1
        name:
          type: string
          example: Sebastian Vettel
        company: 
          type: string
          example: FERRARI
        result:
          type: string
          example: 01:04.415
    Drivers:
      type: array
      items:
         $ref: '#/components/schemas/Driver'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        messages:
          type: string
    
    